# random Sampling

In [2]:
 import numpy as np
import random 

In [3]:
np.random.random(1)

array([0.22914135])

In [5]:
np.random.random((3,3))

array([[0.5917214 , 0.53349497, 0.75484427],
       [0.51805949, 0.97585352, 0.69143111],
       [0.72450051, 0.36923016, 0.18561056]])

In [6]:
np.random.randint(1,4)

2

In [7]:
 np.random.randint(1,4,(4,4))

array([[1, 2, 2, 1],
       [3, 1, 1, 2],
       [1, 1, 3, 1],
       [1, 1, 2, 2]])

In [9]:
np.random.randint(1,4,(2,4,4))

array([[[2, 1, 1, 3],
        [2, 1, 3, 3],
        [3, 1, 1, 1],
        [1, 3, 2, 2]],

       [[2, 1, 2, 2],
        [2, 2, 3, 1],
        [3, 3, 1, 3],
        [3, 2, 1, 1]]])

In [10]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [11]:
 np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [12]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [13]:
np.random.randn(3,3)


array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [15]:
x=[1,2,3,4,5]
np.random.choice(x)

1

In [16]:
x=[1,2,3,4,5]
np.random.choice(x)


1

In [17]:
x=[1,2,3,4,5]
np.random.choice(x)

5

In [19]:
for a in range(20):
    print(np.random.choice(x))

5
1
1
3
5
3
1
1
3
4
1
5
5
1
2
2
5
1
3
2


In [20]:
x

[1, 2, 3, 4, 5]

In [22]:
np.random.permutation(x)

array([1, 5, 3, 2, 4])

In [23]:
np.random.permutation(x)


array([5, 3, 4, 2, 1])