In [7]:
import numpy as np

In [20]:
my_lst=[1,3,2,4,5]
arr=np.array(my_lst)

In [9]:
print(arr)

[1 3 2 4 5]


In [10]:
type(arr)

numpy.ndarray

In [14]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [17]:
arr



array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [18]:
arr.shape

(3, 5)

In [21]:
arr

array([1, 3, 2, 4, 5])

In [22]:
arr[4]

5

In [26]:
arr

array([1, 3, 2, 4, 5])

In [25]:
arr1

array([1, 3, 2, 4, 5])

In [27]:
arr[3:]=100

In [36]:
arr

array([  1,   3,   2, 100, 100])

In [29]:
arr[arr<3]

array([1, 2])

In [32]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
arr1=np.arange(0,10).reshape(2,5)


In [34]:
arr2=np.arange(0,10).reshape(2,5)

In [37]:
arr1*arr2

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [40]:
np.ons((2,5))


AttributeError: module 'numpy' has no attribute 'ons'